participants:
  - name: "Emily Chen"
    role: "Patient Experience Coordinator"
    background: "5 years in healthcare administration, expertise in patient feedback systems"
    is_facilitator: true

tools:
  - name: "Reach Story"
    description: "If we could... we would... So that..."
  - name: "HMW"
    description: "How might we?"
  - name: "WIF"
    description: "What if we?"